#!/data/data/com.termux/files/usr/bin/bash

## https://github.com/adi1090x/termux-style

source ./tspp-config

## Banner
banner () {
    clear
    echo "
    ${BLUE}TERMUX STYLE${RED}++
    ${ORANGE}INSTALLER"
}

## Script Termination
exit_on_signal_SIGINT () {
    { printf "\n\n%s\n" "    ${BLUE}[${RED}*${BLUE}] ${RED}Script interrupted." 2>&1; echo; reset_color; }
    exit 0
}

exit_on_signal_SIGTERM () {
    { printf "\n\n%s\n" "    ${BLUE}[${RED}*${BLUE}] ${RED}Script terminated." 2>&1; echo; reset_color; }
    exit 0
}

trap exit_on_signal_SIGINT SIGINT
trap exit_on_signal_SIGTERM SIGTERM

## Reset terminal colors
reset_color() {
	tput sgr0   # reset attributes
	tput op     # reset color
    return
}

## Prerequisite
prerequisite() {
	{ echo; echo "    ${BLUE}[${RED}*${BLUE}] ${ORANGE}Installing Dependencies..."${CYAN}; echo; }
	if [[ (-f $USR/bin/wget) && (-f $USR/bin/tput) ]]; then
		{ echo "    ${BLUE}[${RED}*${BLUE}] ${GREEN}Dependencies are already Installed!"; }
	else
		{ pkg update -y; pkg install -y git wget ncurses-utils; }
		(type -p wget tput &> /dev/null) && { echo; echo "    ${BLUE}[${RED}*${BLUE}] ${GREEN}Dependencies are succesfully installed!"; } || { echo; echo "    ${BLUE}[${RED}!${BLUE}] ${RED}Error Occured, failed to install dependencies."; echo; reset_color; exit 1; }
	fi
        # Work In Progress
        # wget https://github.com/indra87g/termux-stylepp/releases/download/v1/colors.zip
        # unzip çolors.zip
}

## Install termux-style
install_tspp () {
	echo "    ${BLUE}[${RED}*${BLUE}] ${ORANGE}Installing termux-stylepp..."
	# Delete old files
	if [[ (-L $USR/bin/tspp) && (-d $USR/share/tspp) ]]; then
		echo "    ${BLUE}[${RED}*${BLUE}] ${RED}Deleting files from previous installation...${BLUE}"
		{ rm -r $USR/bin/tspp $USR/share/tspp; echo; }
	fi
	# termux config dir
	if [[ ! -d $TERMUX ]]; then
		mkdir $TERMUX
	else
		cp -r $TERMUX{,.backup}
	fi
	# Coping files
	{ echo "    ${BLUE}[${RED}*${BLUE}] ${ORANGE}Coping files in ${GREEN}$PREFIX/share ${ORANGE}directory..."${BLUE}; }
	{ mkdir $USR/share/tspp; cp -r $DIR/colors $USR/share/tspp; cp -r $DIR/fonts $USR/share/tspp; cp -r $DIR/tspp $USR/share/tspp; cp -r $DIR/tspp-config $USR/share/tspp; }
	{ chmod +x $USR/share/tspp/tspp; ln -s $USR/share/tspp/tspp $USR/bin/tspp; ln -s $USR/share/tspp/tspp-config $USR/bin/tspp-config; }

	# Verify files 
	if [[ (-L $USR/bin/tspp) && (-d $USR/share/tspp) ]]; then
		{ echo; echo "    ${BLUE}[${RED}*${BLUE}] ${GREEN}Successfully Installed."; }
		{ echo "    ${BLUE}[${RED}*${BLUE}] ${GREEN}Now You Can Run This Program By Just typing ${MAGENTA}tspp${GREEN}."; echo; }
		{ reset_color; exit 0; }
	else
		{ echo "    ${BLUE}[${RED}!${BLUE}] ${RED}Error Occured."; echo; reset_color; exit 1; }
	fi
}

## Main
main () {
	banner
	prerequisite
	# Check for previous installation
	if [[ (-L $USR/bin/tspp) && (-d $USR/share/tspp) ]]; then
		{ echo; echo "    ${BLUE}[${RED}!${BLUE}] ${MAGENTA}termux-stylepp ${GREEN}is already installed."; }
		{ read -p "    ${BLUE}[${RED}?${BLUE}] ${ORANGE}Do you wanna re-install it? (y/n): ${GREEN}"; echo; }
		if [[ "$REPLY" =~ ^[y/Y]$ ]]; then
			install_tspp
		else
			{ reset_color; exit; }
		fi
	else
		{ echo; install_tspp; }
	fi
}

main
