#!/data/data/com.termux/files/usr/bin/bash

## https://github.com/adi1090x/termux-style

source ./tspp-config

## Banner
banner () {
    clear
    echo "
    ${BLUE}TERMUX STYLE${RED}++
    ${ORANGE}UNINSTALLER"
}

## Script Termination
exit_on_signal_SIGINT () {
    { printf "\n\n%s\n" "    ${BLUE}[${RED}*${BLUE}] ${RED}Script interrupted." 2>&1; echo; reset_color; }
    exit 0
}

exit_on_signal_SIGTERM () {
    { printf "\n\n%s\n" "    ${BLUE}[${RED}*${BLUE}] ${RED}Script terminated." 2>&1; echo; reset_color; }
    exit 0
}

trap exit_on_signal_SIGINT SIGINT
trap exit_on_signal_SIGTERM SIGTERM

## Reset terminal colors
reset_color() {
	tput sgr0   # reset attributes
	tput op     # reset color
    return
}

## Check for previous installation
uninstall_tspp () {
	banner
	if [[ (-L $USR/bin/tspp) && (-d $USR/share/tspp) ]]; then
		{ echo; echo "    ${BLUE}[${RED}*${BLUE}] ${ORANGE}Uninstalling termux-style..."; echo; }
		{ echo "    ${BLUE}[${RED}*${BLUE}] ${RED}Removing files from $PREFIX/share dir."${BLUE}; }
		{ rm -r $USR/share/tspp $USR/bin/tspp $USR/share/tspp-config $USR/bin/tspp-config; }
		# Verify files
		if [[ (! -L $USR/bin/tspp) && (! -d $USR/share/tspp) ]]; then
			{ echo; echo "    ${BLUE}[${RED}*${BLUE}] ${GREEN}Uninstalled Successfully."; echo; }
			{ reset_color; exit 0; }
		else
			{ echo "    ${BLUE}[${RED}!${BLUE}] ${RED}Error Occured."; echo; reset_color; exit 1; }
		fi
	else
		{ echo; echo "    ${BLUE}[${RED}!${BLUE}] ${MAGENTA}termux-stylepp ${GREEN}is not installed."; echo; }
		{ reset_color; exit 0; }
	fi
}

uninstall_tspp
